### ISSUE TITLE
A small improvement with an automation that takes away thoughts from the user

### ISSUE THREAD

**Issue by Dariosky-01** [TheJoeSmo/Foundry#196] opened 2022-04-22 10:12 UTC
Salutations

An automatic mechanism similar to the one mentioned in publication # 194 could solve the problem of whether old and new people are aware that they would like to create their own rom hack when they find themselves having to assign a gift item that comes out of the treasure chest.

The automation consists only in clicking on the treasure chest after having moved it to the working area, that is the developing level and making available a new button at the top of those under the Foundry menu that is activated only when it is selected the treasure chest, another in addition by counting all those recommended in the old recent publications to self-kill the automatic placement of the functional object that chooses the gift to put inside the treasure chest, with a new window, a GUI for choosing the gift via a drop-down menu inside and a "[✓]" tip next to inside the drop-down menu for choosing the location of that item that allows Mario to exit the level once the treasure chest has been opened and received the gift.
I had in mind that the symbol of the button should have in the design a treasure chest and an asterisk as small as a coin comes out of the mouth of the treasure chest.

Obviously if it is possible, even if I think it could not, it would be good to make these objects disappear from the workspace because so much is a GUI automation that would manage it if it were created (I would say the same thing for the auto-scroll object).

As I advised in that publication, # 194 I want to advise you to be able to make use of the menu that opens with the right button, with an item inside that says: "choose the gift" by making the same window available, that would become available once selected the treasure chest and left click on the new button I mentioned under the menu.

**Comment by TheJoeSmo** [comment] 2022-04-22 23:14
Duplicate of #27

**Closed by TheJoeSmo** 2022-04-22 23:14 UTC
Labels: duplicate
